/* eslint-disable */
/**
 * This file is automatically generated by swagger-to-ts. Do not modify it manually.
 */

import axios from './request';
import type { RequestConfig } from './types';
import type {
  NSPostSourceDailyBulkCreate,
  NSDeleteSourceDailyClear,
  NSPostSourceDailyCreate,
  NSGetSourceDailyList,
  NSGetSourceDaily,
  NSPutSourceDaily,
  NSDeleteSourceDaily
} from './services.types.ts';
/**
 * 接口名称：批量创建Daily
 *
 * @description 接口路径：/source/daily/bulk-create
 * @description 接口分组：源数据 - Daily模块
 */
export const postSourceDailyBulkCreate = (
  body: NSPostSourceDailyBulkCreate.IBody,
  config: RequestConfig = {}
) => axios.post<void>('/source/daily/bulk-create', body, config);
/**
 * 接口名称：清空Daily
 *
 * @description 接口路径：/source/daily/clear
 * @description 接口分组：源数据 - Daily模块
 */
export const deleteSourceDailyClear = (config: RequestConfig = {}) =>
  axios.delete<void>('/source/daily/clear', config);
/**
 * 接口名称：创建Daily
 *
 * @description 接口路径：/source/daily/create
 * @description 接口分组：源数据 - Daily模块
 */
export const postSourceDailyCreate = (
  body: NSPostSourceDailyCreate.IBody,
  config: RequestConfig = {}
) => axios.post<void>('/source/daily/create', body, config);
/**
 * 接口名称：获取Daily列表
 *
 * @description 接口路径：/source/daily/list
 * @description 接口分组：源数据 - Daily模块
 */
export const getSourceDailyList = (
  params: NSGetSourceDailyList.IParams,
  config: RequestConfig = {}
) => axios.get<NSGetSourceDailyList.IRes>('/source/daily/list', { params }, config);
/**
 * 接口名称：获取Daily详情
 *
 * @description 接口路径：/source/daily/{id}
 * @description 接口分组：源数据 - Daily模块
 */
export const getSourceDaily = (id: number, config: RequestConfig = {}) =>
  axios.get<NSGetSourceDaily.IRes>(`/source/daily/${id}`, {}, config);
/**
 * 接口名称：更新Daily
 *
 * @description 接口路径：/source/daily/{id}
 * @description 接口分组：源数据 - Daily模块
 */
export const putSourceDaily = (
  id: number,
  body: NSPutSourceDaily.IBody,
  config: RequestConfig = {}
) => axios.put<void>(`/source/daily/${id}`, body, config);
/**
 * 接口名称：删除Daily
 *
 * @description 接口路径：/source/daily/{id}
 * @description 接口分组：源数据 - Daily模块
 */
export const deleteSourceDaily = (id: number, config: RequestConfig = {}) =>
  axios.delete<void>(`/source/daily/${id}`, {}, config);
